import { SchemaType } from "@google/generative-ai";

/**
 * Gemini Tool Definitions
 * 
 * Defines all tools in Google's Function Calling format for the Gemini API.
 * These tools are used by the Gemini model to interact with the TradeLab system.
 */

export const geminiToolDefinitions = [
  {
    name: "getSchema",
    description:
      "Retrieves the complete database schema including metrics (SQLite/DuckDB) and analytics (ClickHouse) tables, along with Markdown documentation describing the data structure.",
    parameters: {
      type: SchemaType.OBJECT,
      properties: {},
      required: [],
    },
  },

  {
    name: "sql_query_writer",
    description:
      "Creates a JSON file containing a SQL query and target database name. The resulting file can be passed to sql_query_executor or json_sql_query_executor for execution.",
    parameters: {
      type: SchemaType.OBJECT,
      properties: {
        query: {
          type: SchemaType.STRING,
          description: "The SQL query string to execute.",
        },
        database: {
          type: SchemaType.STRING,
          description: "The target database name (optional). Leave empty for default database.",
        },
      },
      required: ["query"],
    },
  },

  {
    name: "sql_query_executor",
    description:
      "Executes a SQL query from a JSON file created by sql_query_writer and returns results as CSV. Useful for large result sets that need to be stored as files.",
    parameters: {
      type: SchemaType.OBJECT,
      properties: {
        file_path: {
          type: SchemaType.STRING,
          description:
            "Absolute or relative path to the JSON file containing { database, query }. This file should be created by sql_query_writer.",
        },
      },
      required: ["file_path"],
    },
  },

  {
    name: "json_sql_query_executor",
    description:
      "Executes a SQL query and returns results as JSON with schema inference. Provides structured output including the inferred JSON schema and sample rows.",
    parameters: {
      type: SchemaType.OBJECT,
      properties: {
        file_path: {
          type: SchemaType.STRING,
          description:
            "Path to JSON file produced by sql_query_writer (contains { database, query }). Either file_path or generated should be provided.",
        },
        generated: {
          type: SchemaType.OBJECT,
          description: "Alternatively, pass the output object from sql_query_writer directly.",
          properties: {
            filePath: {
              type: SchemaType.STRING,
              description: "Path to JSON produced by sql_query_writer.",
            },
            database: {
              type: SchemaType.STRING,
              description: "Target database name (optional).",
            },
            query: {
              type: SchemaType.STRING,
              description: "SQL query string (optional).",
            },
          },
        },
      },
      required: [],
    },
  },

  {
    name: "python_script_writer",
    description:
      "Saves a Python script string to disk (/tmp) so it can be executed by the python_script_executor tool. Automatically fixes hardcoded paths to use environment variables.",
    parameters: {
      type: SchemaType.OBJECT,
      properties: {
        script_content: {
          type: SchemaType.STRING,
          description: "The complete Python script code to write to disk.",
        },
        file_name: {
          type: SchemaType.STRING,
          description:
            "Optional name for the Python script file (without .py extension). Defaults to 'tradelab_analysis_<timestamp>'.",
        },
      },
      required: ["script_content"],
    },
  },

  {
    name: "python_script_executor",
    description:
      "Executes a Python script generated by python_script_writer and returns stdout/stderr output. Can generate images and PDFs that are automatically detected and linked.",
    parameters: {
      type: SchemaType.OBJECT,
      properties: {
        script_path: {
          type: SchemaType.STRING,
          description: "Path to the Python script generated by python_script_writer.",
        },
      },
      required: ["script_path"],
    },
  },

  {
    name: "pdfGenerator",
    description:
      "Generates a professional PDF report from analysis content using Claude's PDF generation skill. Returns a file URL for the generated PDF.",
    parameters: {
      type: SchemaType.OBJECT,
      properties: {
        content: {
          type: SchemaType.STRING,
          description: "The analysis / report content to embed into the PDF.",
        },
        filename: {
          type: SchemaType.STRING,
          description:
            "Optional desired filename for the generated PDF (without .pdf extension). Defaults to 'tradelab_report_<timestamp>'.",
        },
      },
      required: ["content"],
    },
  },
] as const;

export default geminiToolDefinitions;
