/**
 * Groq-compatible tool definitions (OpenAI SDK format)
 * Used for function calling with Groq API via OpenAI SDK
 */

import { ChatCompletionTool } from "openai/resources/chat/completions";

export const groqToolDefinitions: ChatCompletionTool[] = [
  {
    type: "function",
    function: {
      name: "getSchema",
      description:
        "Retrieves the complete database schema including metrics (SQLite/DuckDB) and analytics (ClickHouse) tables, along with Markdown documentation describing the data structure.",
      parameters: {
        type: "object",
        properties: {
          database: {
            type: "string",
            description: "The database to get schema for (optional). Default: returns all databases.",
          },
        },
        required: [],
      },
    },
  },

  {
    type: "function",
    function: {
      name: "sql_query_writer",
      description:
        "Creates a JSON file containing a SQL query and target database name. The resulting file can be passed to sql_query_executor or json_sql_query_executor for execution.",
      parameters: {
        type: "object",
        properties: {
          query: {
            type: "string",
            description: "The SQL query string to execute.",
          },
          database: {
            type: "string",
            description:
              "The target database name (optional). Leave empty for default database.",
          },
        },
        required: ["query"],
      },
    },
  },

  {
    type: "function",
    function: {
      name: "sql_query_executor",
      description:
        "Executes a SQL query from a JSON file created by sql_query_writer and returns results as CSV. Useful for large result sets that need to be stored as files.",
      parameters: {
        type: "object",
        properties: {
          file_path: {
            type: "string",
            description:
              "Absolute or relative path to the JSON file containing { database, query }. This file should be created by sql_query_writer.",
          },
        },
        required: ["file_path"],
      },
    },
  },

  {
    type: "function",
    function: {
      name: "json_sql_query_executor",
      description:
        "Executes a SQL query and returns results as JSON with schema inference. Provides structured output including the inferred JSON schema and sample rows.",
      parameters: {
        type: "object",
        properties: {
          file_path: {
            type: "string",
            description:
              "Path to JSON file produced by sql_query_writer (contains { database, query }). Either file_path or generated should be provided.",
          },
          generated: {
            type: "object",
            description: "Alternatively, pass the output object from sql_query_writer directly.",
            properties: {
              filePath: {
                type: "string",
                description: "Path to JSON produced by sql_query_writer.",
              },
              database: {
                type: "string",
                description: "Target database name (optional).",
              },
              query: {
                type: "string",
                description: "SQL query string (optional).",
              },
            },
          },
        },
        required: [],
      },
    },
  },

  {
    type: "function",
    function: {
      name: "python_script_writer",
      description:
        "Saves a Python script string to disk (/tmp) so it can be executed by the python_script_executor tool. Automatically fixes hardcoded paths to use environment variables.",
      parameters: {
        type: "object",
        properties: {
          script_content: {
            type: "string",
            description: "The complete Python script code to write to disk.",
          },
          file_name: {
            type: "string",
            description:
              "Optional name for the Python script file (without .py extension). Defaults to 'tradelab_analysis_<timestamp>'.",
          },
        },
        required: ["script_content"],
      },
    },
  },

  {
    type: "function",
    function: {
      name: "python_script_executor",
      description:
        "Executes a Python script generated by python_script_writer and returns stdout/stderr output. Can generate images and PDFs that are automatically detected and linked.",
      parameters: {
        type: "object",
        properties: {
          script_path: {
            type: "string",
            description: "Path to the Python script generated by python_script_writer.",
          },
        },
        required: ["script_path"],
      },
    },
  },

  {
    type: "function",
    function: {
      name: "pdfGenerator",
      description:
        "Generates a professional PDF report from analysis content. Returns a file URL for the generated PDF.",
      parameters: {
        type: "object",
        properties: {
          content: {
            type: "string",
            description: "The analysis / report content to embed into the PDF.",
          },
          filename: {
            type: "string",
            description:
              "Optional desired filename for the generated PDF (without .pdf extension). Defaults to 'tradelab_report_<timestamp>'.",
          },
        },
        required: ["content"],
      },
    },
  },
];
