CREATE TABLE risk_profile AS
WITH t AS (SELECT client_id,sum(realized_pnl) FILTER(WHERE _timestamp>=as_of()-INTERVAL '1 day') p1,sum(realized_pnl) FILTER(WHERE _timestamp>=as_of()-INTERVAL '7 days') p7,sum(realized_pnl) FILTER(WHERE _timestamp>=as_of()-INTERVAL '30 days') p30,sum(realized_pnl) FILTER(WHERE _timestamp>=as_of()-INTERVAL '90 days') p90,sum(realized_pnl) FILTER(WHERE _timestamp>=as_of()-INTERVAL '360 days') p360,mode(asset_class) asset,count(DISTINCT symbol) symbols FROM analytics.trades GROUP BY 1),
r AS (SELECT u.client_id,rank() OVER(ORDER BY coalesce(t.p90,0) DESC) pnl_rank,percent_rank() OVER(ORDER BY coalesce(t.p90,0)) percentile FROM analytics.users u LEFT JOIN t USING(client_id)),
d AS (SELECT client_id,greatest(0,-min(pnl)) loss,stddev_pop(pnl) volatility,count(*) FILTER(WHERE pnl<-10000) loss_days FROM metric_helpers.daily WHERE day>=as_of()::DATE-INTERVAL '90 days' GROUP BY 1),
cumulative AS (SELECT client_id,day,sum(pnl) OVER(PARTITION BY client_id ORDER BY day) c FROM metric_helpers.daily WHERE day>=as_of()::DATE-INTERVAL '90 days'),
drawdown AS (SELECT client_id,max(dd) dd FROM (SELECT client_id,greatest(0,max(c) OVER(PARTITION BY client_id ORDER BY day))-c dd FROM cumulative) GROUP BY 1),
s AS (SELECT client_id,max(volume_share)>.8 concentrated,sum(volume_share*volume_share) hhi FROM (SELECT client_id,volume/sum(volume) OVER(PARTITION BY client_id) volume_share FROM metric_helpers.symbol90) GROUP BY 1),
b AS (SELECT client_id,bool_or(pnl<-10000 AND next_volume>avg_volume*2) changed FROM (SELECT *,lead(volume) OVER(PARTITION BY client_id ORDER BY day) next_volume,avg(volume) OVER(PARTITION BY client_id) avg_volume FROM metric_helpers.daily WHERE day>=as_of()::DATE-INTERVAL '90 days') GROUP BY 1)
SELECT u.client_id,coalesce(t.p1,0) pnl_1d,coalesce(t.p7,0) pnl_7d,coalesce(t.p30,0) pnl_30d,coalesce(t.p90,0) pnl_90d,t.asset preferred_asset_class,coalesce(t.p360,0) pnl_360d,coalesce(t.p90,0) total_pnl_90d,r.pnl_rank user_rank_by_pnl_90d,r.percentile pnl_percentile_90d,
 coalesce(d.loss,0) max_single_day_loss_90d,d.volatility pnl_volatility_90d,coalesce(d.loss_days,0) large_loss_day_count_90d,coalesce(drawdown.dd,0) max_pnl_drawdown_90d,coalesce(b.changed,false) post_large_loss_behavior_change_flag,coalesce(s.concentrated,false) is_concentrated_trader_flag,s.hhi trade_concentration_index_90d,coalesce(t.symbols,0) lifetime_distinct_symbols_traded
FROM analytics.users u LEFT JOIN t USING(client_id) LEFT JOIN r USING(client_id) LEFT JOIN d USING(client_id) LEFT JOIN drawdown USING(client_id) LEFT JOIN s USING(client_id) LEFT JOIN b USING(client_id);
