CREATE TABLE platform_health AS
WITH o AS (SELECT client_id,avg((status='REJECTED')::INTEGER) rejected,avg((filled_quantity=0)::INTEGER) unfilled,
 avg(date_diff('second',_timestamp,modified_at)/60.0) FILTER(WHERE status='CANCEL_CONFIRMED') cancel_life FROM analytics.orders WHERE _timestamp>=as_of()-INTERVAL '30 days' GROUP BY 1),
t AS (SELECT t.client_id,count(*) FILTER(WHERE t._timestamp>=as_of()-INTERVAL '30 days') trades30,avg(date_diff('second',o._timestamp,t._timestamp)) FILTER(WHERE t._timestamp>=as_of()-INTERVAL '30 days') fill_time FROM analytics.trades t JOIN analytics.orders o USING(order_id) GROUP BY 1),
f AS (SELECT client_id,avg(filled_quantity/nullif(quantity,0)) fill_ratio,sum(price*quantity) FILTER(WHERE status='CANCEL_CONFIRMED') cancelled FROM analytics.orders WHERE _timestamp>=as_of()-INTERVAL '90 days' GROUP BY 1),
e AS (SELECT client_id,avg((http_status>=400 AND http_status<500)::INTEGER) errors,avg(http_duration_ms) duration,count(*) FILTER(WHERE http_status>=400 AND http_status<500) error_count,avg(http_duration_ms) FILTER(WHERE http_url='/api/v1/dashboard/pins') dashboard FROM analytics.events WHERE event_name='HTTP Request' AND _timestamp>=as_of()-INTERVAL '30 days' GROUP BY 1),
g AS (SELECT (SELECT count(*) FROM log_aggregator.logs WHERE service='auth' AND list_contains(string_values,'Token expired') AND _timestamp>=as_of()-INTERVAL '30 days') expired,
 (SELECT symbol FROM analytics.trades WHERE _timestamp>=as_of()-INTERVAL '30 days' GROUP BY symbol ORDER BY sum(quantity*price) DESC,symbol LIMIT 1) most_traded,
 (SELECT symbol FROM analytics.trades WHERE _timestamp>=as_of()-INTERVAL '30 days' GROUP BY symbol ORDER BY count(DISTINCT client_id) FILTER(WHERE _timestamp>=as_of()-INTERVAL '3 days')/3.0-count(DISTINCT client_id)/30.0 DESC,symbol LIMIT 1) trending)
SELECT u.client_id,g.expired total_session_expirations_30d,g.most_traded most_traded_instrument_by_volume_30d,g.trending instrument_with_largest_trader_increase,e.errors client_error_rate_30d,e.duration avg_api_response_time_ms_30d,t.fill_time avg_time_to_fill_seconds_30d,e.error_count/nullif(t.trades30,0) error_to_trade_ratio_30d,e.dashboard avg_time_to_load_dashboard_ms,o.rejected order_rejection_rate_30d,o.unfilled orders_not_traded_ratio_30d,o.cancel_life avg_order_life_to_cancel_minutes,f.fill_ratio avg_trade_fill_ratio_90d,coalesce(f.cancelled>(SELECT quantile_cont(cancelled,.95) FROM f),false) is_high_volume_cancelled_flag
FROM analytics.users u CROSS JOIN g LEFT JOIN o USING(client_id) LEFT JOIN t USING(client_id) LEFT JOIN f USING(client_id) LEFT JOIN e USING(client_id);
